<Project>
  <PropertyGroup>
    <TargetFramework Condition="'$(MSBuildProjectName)' != 'SeniorCare.Mobile'">net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <InvariantGlobalization>false</InvariantGlobalization>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
